import React,{useEffect,useState}from'react';
import{NativeEventEmitter,NativeModules,PermissionsAndroid,Platform,Pressable,StyleSheet,Text,View}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import AppV2 from'./AppV2';
import{subscribeToZaycommQr,startZaycommQrScanner,stopZaycommQrScanner}from'./src/scanner/qrEvents';
import{establishIntroducedPeer}from'./src/core/peerEstablishment';

type Peer={id:string;address:string};
type Identity={nodeId:string;publicKey:string};
const nativeBle=NativeModules.ZaycommBle;
const bleEvents=nativeBle?new NativeEventEmitter(nativeBle):null;
const TRUSTED_KEY='zaycomm.trustedPeers';
const DISMISSED_KEY='zaycomm.homeAuthDismissed';

export default function AppV3(){
 const[peer,setPeer]=useState<Peer|null>(null),[linked,setLinked]=useState(false),[manualConnecting,setManualConnecting]=useState(false),[manualError,setManualError]=useState(''),[dismissed,setDismissed]=useState<string[]>([]),[authenticatedAddress,setAuthenticatedAddress]=useState<string|null>(null),[step,setStep]=useState<'prompt'|'scanning'|'verified'>('prompt'),[identity,setIdentity]=useState<Identity|null>(null),[error,setError]=useState('');
 useEffect(()=>{AsyncStorage.getItem(DISMISSED_KEY).then(v=>{try{setDismissed(v?JSON.parse(v):[])}catch{setDismissed([])}})},[]);
 useEffect(()=>{if(!bleEvents)return;const ad=bleEvents.addListener('ZaycommBleAdvertisement',(p:Peer)=>{setPeer(p);setAuthenticatedAddress(null);setManualError('');setManualConnecting(false)});const link=bleEvents.addListener('ZaycommBleConnectionChanged',(e:{address:string;connected:boolean})=>{if(e.connected){setLinked(true);setManualConnecting(false);setManualError('')}else{setLinked(false);setManualConnecting(false);setManualError('');setAuthenticatedAddress(null);setPeer(current=>current?.address===e.address?null:current)}});return()=>{ad.remove();link.remove()}},[]);
 useEffect(()=>subscribeToZaycommQr(event=>{setIdentity({nodeId:event.identity.identity.nodeId,publicKey:event.identity.identity.publicKey});setStep('verified');setError('')},()=>peer?.address),[peer]);
 const visible=!!peer&&linked&&!dismissed.includes(peer.address)&&authenticatedAddress!==peer.address;
 const manualVisible=!!peer&&!linked&&!dismissed.includes(peer.address);
 useEffect(()=>{if(visible){setStep('prompt');setIdentity(null);setError('')}},[visible]);
 const dismiss=async()=>{if(!peer)return;const next=[...new Set([...dismissed,peer.address])];setDismissed(next);await AsyncStorage.setItem(DISMISSED_KEY,JSON.stringify(next));await stopZaycommQrScanner();setPeer(null);setAuthenticatedAddress(null);setManualError('')};
 const manualConnect=async()=>{if(!peer||!nativeBle)return;setManualConnecting(true);setManualError('');try{await nativeBle.connect(peer.address)}catch(e){setManualConnecting(false);setManualError(`Manual connection failed: ${String(e)}`)}};
 const begin=async()=>{setError('');if(Platform.OS==='android'){const r=await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA);if(r!==PermissionsAndroid.RESULTS.GRANTED){setError('Camera permission is required to authenticate this node.');return}}try{const ok=await startZaycommQrScanner();if(!ok){setError('The QR camera is unavailable.');return}setStep('scanning')}catch(e){setError(`Unable to start QR scanner: ${String(e)}`)}};
 const cancel=async()=>{await stopZaycommQrScanner();setStep('prompt')};
 const trust=async()=>{if(!identity||!peer)return;try{await establishIntroducedPeer(identity.nodeId);const current=JSON.parse((await AsyncStorage.getItem(TRUSTED_KEY))||'[]');const next=[...new Set([...current,identity.nodeId])];await AsyncStorage.setItem(TRUSTED_KEY,JSON.stringify(next));setAuthenticatedAddress(peer.address);setStep('prompt');setIdentity(null);setError('');await stopZaycommQrScanner()}catch(e){setError(`Unable to establish peer: ${String(e)}`)}};
 return <><AppV2/>{manualVisible&&<View style={s.manualBackdrop}><View style={s.manualCard}><View style={s.header}><View><Text style={s.kicker}>NODE DISCOVERED</Text><Text style={s.title}>Connection available</Text></View><Pressable onPress={dismiss}><Text style={s.close}>×</Text></Pressable></View><Text style={s.copy}>Automatic connection is active. If it has not connected, you can establish the BLE link manually.</Text><View style={s.node}><View style={s.dot}/><View style={{flex:1}}><Text style={s.label}>DISCOVERED NODE</Text><Text style={s.id}>{peer.id||peer.address}</Text><Text style={s.status}>BLE DISCOVERED · NOT LINKED</Text></View></View><Pressable style={s.button} onPress={manualConnect} disabled={manualConnecting}><Text style={s.buttonText}>{manualConnecting?'CONNECTING…':'CONNECT MANUALLY'}</Text></Pressable>{manualError!==''&&<Text style={s.error}>{manualError}</Text>}</View></View>}{visible&&<View style={s.backdrop}><View style={s.card}><View style={s.header}><View><Text style={s.kicker}>NEW NODE DETECTED</Text><Text style={s.title}>Establish peer</Text></View><Pressable onPress={dismiss}><Text style={s.close}>×</Text></Pressable></View><Text style={s.copy}>A BLE link is active. The node can now be established as a peer. Use the existing Zaycomm identity QR when the other device is not already established.</Text><View style={s.node}><View style={s.dot}/><View style={{flex:1}}><Text style={s.label}>BLE LINKED NODE</Text><Text style={s.id}>{peer.id||peer.address}</Text></View></View>{step==='prompt'&&<Pressable style={s.button} onPress={begin}><Text style={s.buttonText}>ESTABLISH WITH QR</Text></Pressable>}{step==='scanning'&&<View style={s.scanBox}><Text style={s.scanTitle}>CAMERA ACTIVE</Text><Text style={s.scanCopy}>Hold the other device's Zaycomm identity QR inside the camera frame.</Text><Pressable style={s.secondary} onPress={cancel}><Text style={s.secondaryText}>CANCEL SCAN</Text></Pressable></View>}{step==='verified'&&identity&&<View style={s.verify}><Text style={s.kicker}>IDENTITY READY</Text><Text style={s.verifyId}>{identity.nodeId}</Text><Text style={s.scanCopy}>The remote node identity was captured and bound to the active BLE peer. Confirm to establish this peer.</Text><Pressable style={s.button} onPress={trust}><Text style={s.buttonText}>ESTABLISH PEER</Text></Pressable></View>}{error!==''&&<Text style={s.error}>{error}</Text>}</View></View>}</>;
}

const s=StyleSheet.create({manualBackdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(3,6,20,.58)',justifyContent:'flex-end',zIndex:998},manualCard:{backgroundColor:'#121a3d',borderTopLeftRadius:28,borderTopRightRadius:28,borderWidth:1,borderColor:'#29345f',padding:22,paddingBottom:30},backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(3,6,20,.72)',justifyContent:'flex-end',zIndex:999},card:{backgroundColor:'#121a3d',borderTopLeftRadius:28,borderTopRightRadius:28,borderWidth:1,borderColor:'#29345f',padding:22,paddingBottom:30},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},kicker:{fontSize:10,fontWeight:'800',letterSpacing:1.7,color:'#57e0ff'},title:{fontSize:23,fontWeight:'800',color:'#eef1ff',marginTop:6},close:{fontSize:30,lineHeight:28,color:'#8891bd'},copy:{fontSize:13,lineHeight:20,color:'#aeb6dc',marginTop:14},node:{marginTop:16,padding:14,borderRadius:16,borderWidth:1,borderColor:'#29345f',flexDirection:'row',alignItems:'center',gap:12},dot:{width:10,height:10,borderRadius:5,backgroundColor:'#4ade9c'},label:{fontSize:9,fontWeight:'800',letterSpacing:1,color:'#8891bd'},id:{fontFamily:Platform.OS==='ios'?'Menlo':'monospace',fontSize:13,color:'#eef1ff',marginTop:4},status:{fontSize:9,fontWeight:'800',letterSpacing:.8,color:'#ffb454',marginTop:5},button:{marginTop:18,padding:16,borderRadius:15,backgroundColor:'#57e0ff',alignItems:'center'},buttonText:{fontSize:11,fontWeight:'900',letterSpacing:1,color:'#07101e'},secondary:{marginTop:14,padding:13,borderRadius:14,borderWidth:1,borderColor:'#39456f',alignItems:'center'},secondaryText:{fontSize:10,fontWeight:'800',letterSpacing:1,color:'#aeb6dc'},scanBox:{marginTop:16,padding:18,borderRadius:18,borderWidth:1,borderColor:'#57e0ff55',backgroundColor:'#0d1330'},scanTitle:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:'#57e0ff'},scanCopy:{fontSize:12,lineHeight:19,color:'#aeb6dc',marginTop:7},verify:{marginTop:16,padding:17,borderRadius:18,borderWidth:1,borderColor:'#4ade9c55',backgroundColor:'#0d2a2a'},verifyId:{fontFamily:Platform.OS==='ios'?'Menlo':'monospace',fontSize:18,fontWeight:'800',color:'#eef1ff',marginTop:8},error:{fontSize:12,lineHeight:18,color:'#ff6b7d',marginTop:12}});