import React,{useEffect,useState}from'react';
import{Alert,NativeEventEmitter,NativeModules,PermissionsAndroid,Platform,Pressable,StyleSheet,Text,View}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{subscribeToZaycommQr,startZaycommQrScanner,stopZaycommQrScanner}from'./src/scanner/qrEvents';

type Peer={id:string;address:string};
type Props={visible:boolean;peer:Peer;onDismiss:()=>void};
type Identity={nodeId:string;publicKey:string};
const nativeBle=NativeModules.ZaycommBle;
const bleEvents=nativeBle?new NativeEventEmitter(nativeBle):null;
const TRUSTED_KEY='zaycomm.trustedPeers';

export default function HomeAuthenticationOverlay({visible,peer,onDismiss}:Props){
 const[step,setStep]=useState<'prompt'|'scanning'|'verified'>('prompt');
 const[identity,setIdentity]=useState<Identity|null>(null);const[error,setError]=useState('');
 useEffect(()=>{if(!visible)return;setStep('prompt');setIdentity(null);setError('');const sub=subscribeToZaycommQr(({identity:result})=>{if(!result)return;setIdentity(result.identity);setStep('verified');setError('')});return()=>{sub.remove();stopZaycommQrScanner().catch(()=>{})}},[visible]);
 if(!visible)return null;
 const begin=async()=>{setError('');if(Platform.OS==='android'){const r=await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA);if(r!==PermissionsAndroid.RESULTS.GRANTED){setError('Camera permission is required to authenticate this node.');return}}const ok=await startZaycommQrScanner();if(!ok){setError('The QR camera is unavailable. Open Pair and try again.');return}setStep('scanning')};
 const trust=async()=>{if(!identity)return;try{const current=JSON.parse((await AsyncStorage.getItem(TRUSTED_KEY))||'[]');const next=[...new Set([...current,identity.nodeId])];await AsyncStorage.setItem(TRUSTED_KEY,JSON.stringify(next));await stopZaycommQrScanner();Alert.alert('Node authenticated',`${identity.nodeId} is now trusted on this device.`);onDismiss()}catch(e){setError(`Unable to save trust: ${String(e)}`)}};
 return <View style={s.backdrop}><View style={s.card}><View style={s.header}><View><Text style={s.kicker}>NEW NODE DETECTED</Text><Text style={s.title}>Authenticate device</Text></View><Pressable onPress={onDismiss}><Text style={s.close}>×</Text></Pressable></View><Text style={s.copy}>A BLE link is active. Authentication is separate from transport: scan the other device's Zaycomm identity QR to establish trust.</Text><View style={s.node}><View style={s.dot}/><View style={{flex:1}}><Text style={s.label}>BLE LINKED NODE</Text><Text style={s.id}>{peer.id||peer.address}</Text></View></View>{step==='prompt'&&<Pressable style={s.button} onPress={begin}><Text style={s.buttonText}>SCAN IDENTITY QR</Text></Pressable>}{step==='scanning'&&<View style={s.scanBox}><Text style={s.scanTitle}>CAMERA ACTIVE</Text><Text style={s.scanCopy}>Hold the other device's Zaycomm QR inside the camera frame.</Text><Pressable style={s.secondary} onPress={async()=>{await stopZaycommQrScanner();setStep('prompt')}}><Text style={s.secondaryText}>CANCEL SCAN</Text></Pressable></View>}{step==='verified'&&identity&&<View style={s.verify}><Text style={s.kicker}>IDENTITY VERIFIED</Text><Text style={s.verifyId}>{identity.nodeId}</Text><Text style={s.scanCopy}>The QR is a valid Zaycomm identity. Trust it only after confirming it is the same device shown above.</Text><Pressable style={s.button} onPress={trust}><Text style={s.buttonText}>TRUST THIS NODE</Text></Pressable></View>}{error!==''&&<Text style={s.error}>{error}</Text>}</View></View>
}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(3,6,20,.72)',justifyContent:'flex-end',zIndex:999},card:{backgroundColor:'#121a3d',borderTopLeftRadius:28,borderTopRightRadius:28,borderWidth:1,borderColor:'#29345f',padding:22,paddingBottom:30},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},kicker:{fontSize:10,fontWeight:'800',letterSpacing:1.7,color:'#57e0ff'},title:{fontSize:23,fontWeight:'800',color:'#eef1ff',marginTop:6},close:{fontSize:30,lineHeight:28,color:'#8891bd'},copy:{fontSize:13,lineHeight:20,color:'#aeb6dc',marginTop:14},node:{marginTop:16,padding:14,borderRadius:16,borderWidth:1,borderColor:'#29345f',flexDirection:'row',alignItems:'center',gap:12},dot:{width:10,height:10,borderRadius:5,backgroundColor:'#4ade9c'},label:{fontSize:9,fontWeight:'800',letterSpacing:1,color:'#8891bd'},id:{fontFamily:Platform.OS==='ios'?'Menlo':'monospace',fontSize:13,color:'#eef1ff',marginTop:4},button:{marginTop:18,padding:16,borderRadius:15,backgroundColor:'#57e0ff',alignItems:'center'},buttonText:{fontSize:11,fontWeight:'900',letterSpacing:1,color:'#07101e'},secondary:{marginTop:14,padding:13,borderRadius:14,borderWidth:1,borderColor:'#39456f',alignItems:'center'},secondaryText:{fontSize:10,fontWeight:'800',letterSpacing:1,color:'#aeb6dc'},scanBox:{marginTop:16,padding:18,borderRadius:18,borderWidth:1,borderColor:'#57e0ff55',backgroundColor:'#0d1330'},scanTitle:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:'#57e0ff'},scanCopy:{fontSize:12,lineHeight:19,color:'#aeb6dc',marginTop:7},verify:{marginTop:16,padding:17,borderRadius:18,borderWidth:1,borderColor:'#4ade9c55',backgroundColor:'#0d2a2a'},verifyId:{fontFamily:Platform.OS==='ios'?'Menlo':'monospace',fontSize:18,fontWeight:'800',color:'#eef1ff',marginTop:8},error:{fontSize:12,lineHeight:18,color:'#ff6b7d',marginTop:12}}
